version: '3'

services:
  url-shortener:
    image: 'url-shortener:latest'
    build:
      context: .
    container_name: url-shortener-app
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=test123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    ports:
      - "8190:8080"
      - "5005:5005"
    volumes:
      - ./target/url-shortener-0.0.1-SNAPSHOT.jar:/application.jar

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: url_shortener
    ports:
      - "5436:5432"

networks:
  app-network:
    driver: bridge